### ISSUE TITLE
Address New User Experience

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#1]
In the admin, a pseudo-menu is auto-created on new installs. I'm thinking it might be worth actually creating an actual default menu that can be assigned to the theme location right away then edited. Currently, users would need to start out by creating a new menu and adding items to it, which creates discovery issues. We should consider all of the discussions and user testing done for the menus refresh in WordPress 3.6 here as well.

**Comment by voldemortensen** [comment]
I really like the idea of better NUX. I think creating a default menu will not only address discovery issues, but also simplify the process. I remember when I started with WordPress, getting rid of the duplicate "Home" page took a lot longer than it should have.

**Comment by Fab1en** [comment]
The problem with this approach is that you completely hide the fallback behaviour that normally happens when there is no menu : the list of site Pages is displayed.

Having said that, the issue of menu admin UI discovery really exists. I think the best approach would be to put a "edit this menu" button next to the menu on the front-end, like what already exists to edit posts and pages. That solution would need some work from theme authors, but that would be the best way for new users to discover how they can modify a menu.
