### ISSUE TITLE
Menu Item Type Extensibility 

### ISSUE THREAD

**Issue by sevenspark** [voldemortensen/menu-customizer#103]
Can we add a way to extend available menu items?  

In the Appearance > Menus screen, we can use add_meta_box to insert custom menu item types.

However, in available_items_template(), there isn't the ability to add any additional types of menu items (though I see there is an @todo note regarding add_meta_box)

Right now, the Menu Customizer doesn't interfere with any custom items added in Appearance > Menus as far as I can tell, so that's good.  But it'd be nice to be able to add them via the Customizer interface as well.

I think just adding an action hook would probably be all we'd need.

Thanks! :)

**Comment by westonruter** [comment]
Yes, this is something that needs to be added at some point. I have an initial TODO for where we can pick up additional controls added: https://github.com/voldemortensen/menu-customizer/blob/96b56a0e0a35073aa8beaecade2a568c555a9422/menu-customizer.js#L988

What comes to mind to implement this is:

1. Ability to add new controls to the template.
1. Connect the new controls to the setting, with custom validation logic.
1. Add support for filtering the postmeta for a given `nav_menu_item` so that any custom fields will get previewed as expected.
1. Update the `WP_Customize_Nav_Menu_Item_Setting` to store any non-core attributes in postmeta, and draw from postmeta when obtaining the setting value.

The first two can be done in JS now, although there isn't a nice API for doing it.

**Comment by designsimply** [comment]
Moved to https://core.trac.wordpress.org/ticket/32712
