### ISSUE TITLE
Add theme location names to menu section titles

### ISSUE THREAD

**Issue by celloexpressions** [voldemortensen/menu-customizer#24]
There should be some sort of a mechanism here to quickly see which menus are actually being used, from the list of menus.

**Comment by celloexpressions** [comment]
Looking like it'll make the most sense to do this in JS.

**Comment by valendesigns** [comment]
Something like adding a class to highlight the in-use menus?

**Comment by celloexpressions** [comment]
So I actually just pushed a first-pass here while I was offline. It's super ugly but functional. I'd like to show the name of the menu location if there's a way to do it that isn't so ugly, but we could just do some other visual indicator. It needs to be very clear though, since the goal is only to cover theme locations and not menus in use in widgets (which gets super messy). Want to play around with the design of it?

**Comment by valendesigns** [comment]
Sure, I'll pull and play. 😃

**Comment by valendesigns** [comment]
It almost feel like this shouldn't be done. Instead since #23 plans to bring back the location checkboxes and #25 will remove the delete link when active, all we should be doing here is highlighting the control in some way to slightly separate it visually from the rest of the menus. The are already issues with this current implementation. For example, when you edit a title the location is removed. Or if the menu name is long the location is being overlapped by the control toggle arrow. Nothing major, but could all be avoided if we chose a simpler approach.

**Comment by valendesigns** [comment]
Alternatively, we could fix the issues I mentioned above and display block `.menu-in-location` so it sits on the next line. Remove the icon and have the text say something like `(Currently set to: Primary Menu)` which would be more inline with how menus in core do it.

**Comment by valendesigns** [comment]
![screen shot 2015-05-19 at 11 57 33 pm](https://cloud.githubusercontent.com/assets/62798/7720491/de7bd7b6-fe82-11e4-8997-0f70004572af.png)

**Comment by valendesigns** [comment]
I'm just going to go with this design in the screen shot above for now, we can iterate on it later.

**Comment by celloexpressions** [comment]
That design looks pretty good to me.
