### ISSUE TITLE
Item ordering is destroyed when a new item is added after reordering items (depends on #67)

### ISSUE THREAD

**Issue by designsimply** [voldemortensen/menu-customizer#42]
Steps to reproduce:

1. Open any menu in Appearance > Customize > Menus
1. Add several menu items and reorder them
1. Add a new menu item

<strong>Result:</strong> when a new menu item is added in the last step, the menu reordering from the previous step is destroyed.

Screencast: <a href="https://cloudup.com/cRQM_OcinMU">1m3s</a>

![screen shot 2015-05-27 at wed may 27 10 53 31 am](https://cloud.githubusercontent.com/assets/1119271/7839389/2cbc987e-0460-11e5-9383-f0dad9046c03.png)
<sup>Seen at http://whatisinfinity.com/wp-admin/customize.php using WP 4.3-alpha-32600 and Menu Customizer plugin 0.4 (6a6fca3) on Firefox 38.0.1 on Mac OSX 10.10.3</sup>

Found during user testing.

**Comment by designsimply** [comment]
This problem showed up in a user test. Here's the related video snippet for reference: [22s](https://cloudup.com/cHQFwaJ2dtv) 

Note: pay close attention to the ordering in the controls on the left, the user didn't even notice at all that they switched.

<sup>Pulled from the test at https://make.wordpress.org/design/2015/05/27/customizer-menus-user-testing/#comment-24592 using WP 4.3-alpha-32600 and the Menu Customizer 0.4 (6a6fca3).</sup>

**Comment by westonruter** [comment]
The re-sorting is probably being done here: https://github.com/voldemortensen/menu-customizer/blob/44ef9d6fd9e303dd1a3fb60bb6ccb3110254e02e/menu-customizer.js#L1561-L1580

As to why the order is getting destroyed, I suspect it may be related to nav menu items getting cloned and their menu item ID then getting updated. I notice often that `getMenuItemControls` will return some undefined values (which I put in a superficial fix in #63), which the sort logic is returning `undefined`, which probably translates into an undefined order. I think `getMenuItemControl` is not able to find all of the new `menuItemControls`.

So, all of this to say, I think it will also be fixed by #67 which will involve the elimination of cloning posts.

**Comment by celloexpressions** [comment]
This should be fixed now, can someone confirm?

**Comment by designsimply** [comment]
Tested and confirmed fixed using WordPress 4.3-alpha-32784 and Menu Customizer plugin 0.6-20150615.
