### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by valendesigns** [voldemortensen/menu-customizer#44]
Clear out all the build errors created when JS sniffs were added to Travis.

**Comment by valendesigns** [comment]
So we need to circle back on this for the camel case issues.

**Comment by celloexpressions** [comment]
Not sure how the workflow works for seeing the errors, and I don't have time until probably Wednesday at this point to circle back to this, but I'm also not thinking that this is a critical thing to change. If anyone else has time to circle back to this feel free, otherwise I'm inclined to leave it.

**Comment by westonruter** [comment]
This is now done.
